### ISSUE TITLE
How to generate bearer token

### ISSUE THREAD

**Issue by sammycakes** [cljung/java-rest-api#1]
Thanks for the great example! One question, how do you suggest generating a bearer token to use with this code? In the example this code is based on (https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-sample) I can generate an ID token, but I get an error trying to use that ID token as a bearer token of course.

**Comment by sammycakes** [comment]
Nvm, I requeted a bearer token with Postman ... I'm having a frustrating problem when trying to use my token with an "invalid audience" error, but I'll close this issue.

**Comment by AntonKovbasa** [comment]
> Nvm, I requeted a bearer token with Postman ... I'm having a frustrating problem when trying to use my token with an "invalid audience" error, but I'll close this issue.

Did you manage to solve this problem?
